<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>specapi</string>
	</array>
	<key>name</key>
	<string>SpecAPI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>comment</key>
			<string>Comment Blocks</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.documentation.specapi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Comment Tags</string>
					<key>match</key>
					<string>\@[\w]+</string>
					<key>name</key>
					<string>entity.name.tag.specapi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.specapi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.other.specapi</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>(api|get|put|post|delete|package|params|response|body|entity|enum)</string>
			<key>name</key>
			<string>keyword.operator.specapi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>(string|int|long|boolean|double|float)</string>
			<key>name</key>
			<string>storage.type.specapi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Url</string>
			<key>match</key>
			<string>http(s)?\:\/\/[^\{]+</string>
			<key>name</key>
			<string>entity.other.attribute-name.specapi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Path</string>
			<key>match</key>
			<string>\/[^\{]+</string>
			<key>name</key>
			<string>constant.other.specapi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Identifier</string>
			<key>match</key>
			<string>\w+(\.\w+)?</string>
			<key>name</key>
			<string>entity.name.function.specapi</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.specapi</string>
	<key>uuid</key>
	<string>fe2695a1-dbb4-4186-95e2-14aa4f38e8b7</string>
</dict>
</plist>
